FROM node:alpine

WORKDIR /app

COPY package.json .

RUN npm install 

COPY . .

CMD ["npm", "start"]
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app mundhrakeshav/frontend
#                          -> Don't map node_modules    -> Map rest of directory